services:
  pawload:
    image: ghcr.io/kemalasliyuksek/pawload:latest
    restart: unless-stopped
    container_name: pawload
    ports:
      - "9002:80"
    environment:
      COBALT_API_URL: "https://your-cobalt-instance.example.com"
